**About the dataset**

WAQI project data-set is updated 3 times a day, and covering about 380 major cities in the world.

The data for each major cities is based on the average (median) of several stations. The data set provides min, max, median and standard deviation for each of the air pollutant species (PM2.5,PM10, Ozone ...) as well as meteorological data (Wind, Temperature, ...).

All air pollutant species are converted to the US EPA standard (i.e. no raw concentrations). All dates are UTC based.

The count column is the number of samples used for calculating the median and standard deviation.

The city-median value is computed per day using all AQI values for available stations.

More Info: https://aqicn.org/data-platform/covid19/

**WORKING STEPS OF THE WITH DATASET**


1.   Group the content of the dataset based on date, country and city(4 dataset separately)

*   Each unique specie will become new column
*   Values of species if found duplicate max value all be assigned among the values


2.   Combine 4 dataframe into one
3.   Export the combine dataset

***Additional Information***

01/01/2024 - 31-12-2024


Dataset 1 starting and end date(mm/dd/yyyy) : 12/26/2022-4/2/2023

Dataset 2 starting and end date(mm/dd/yyyy) : 3/27/2023-7/2/2023

Dataset 3 starting and end date(mm/dd/yyyy) : 6/26/2023-10/1/2023

Dataset 4 starting and end date(mm/dd/yyyy) : 9/25/2023-12/31/2023


2023:

12/26/2022-4/2/2023

3/27/2023-7/2/2023

6/26/2023-10/1/2023

9/25/2023-12/31/2023

2022:

3/28/2022-7/3/2022

6/27/2022-10/2/2022

9/26/2022-1/1/2023

2021:

12/28/2020-4/4/2021

3/29/2021-7/4/2021

6/28/2021-10/3/2021

9/27/2021-1/2/2022

2020:

12/30/2019-4/5/2020

3/30/2020-7/5/2020

6/29/2020-10/4/2020

9/28/2020-1/3/2021

2019:

12/31/2018-3/31/2019

4/1/2019-6/30/2019

7/1/2019-10/6/2019

9/30/2019-1/5/2020

2018:

1/1/2018-7/1/2018

2017:

12/26/2016-7/2/2017

2016:

12/28/2015-7/3/2016

2015:

12/29/2014-7/5/2015

In [1]:
import pandas as pd
import numpy as np

# 2024

In [2]:
# Load the dataset into a DataFrame
raw_data_2024 = pd.read_csv(r'/kaggle/input/raw-data/airqualitydata-2024.csv')

# print the shape
print(raw_data_2024.shape)

#runs the first 5 rows
raw_data_2024.head()

(1048571, 5)

        Date Country     City Specie    max
0  4/15/2024      JP  Fukuoka     o3   46.5
1  4/20/2024      JP  Fukuoka     o3   45.6
2  1/31/2024      JP  Fukuoka     o3   36.8
3  2/25/2024      JP  Fukuoka     o3   37.6
4   8/9/2024      JP  Fukuoka     o3  101.5

In [3]:
# Convert 'Date' to datetime
raw_data_2024['Date'] = pd.to_datetime(raw_data_2024['Date'])

In [4]:
raw_data_2024.shape

(1048571, 5)

In [5]:
# Pivot the data
data_df_2024 = raw_data_2024.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [6]:
print(data_df_2024.shape)
data_df_2024.head()

(102587, 19)

Specie,Date,Country,City,co,dew,humidity,neph,no2,o3,pm10,pm25,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2024-01-01,AE,Abu Dhabi,0.1,20.0,88.0,NaN,31.3,39.9,57.0,87.0,NaN,1019.0,11.5,232.0,NaN,NaN,NaN,6.6
1,2024-01-01,AE,Dubai,18.5,20.0,88.0,NaN,25.2,39.9,77.0,151.0,NaN,1019.0,19.1,27.0,NaN,NaN,NaN,6.6
2,2024-01-01,AR,Buenos Aires,4.7,19.0,82.6,NaN,7.4,16.7,29.0,59.0,99.0,1014.6,6.6,28.7,NaN,157.5,17.0,9.8
3,2024-01-01,AU,Adelaide,2.6,16.9,82.3,NaN,10.6,13.0,27.0,72.0,NaN,1017.8,0.6,29.3,NaN,NaN,18.7,13.0
4,2024-01-01,AU,Brisbane,2.1,22.0,100.0,NaN,9.6,15.1,46.0,98.0,23.5,1019.2,0.6,25.3,NaN,265.0,16.7,6.7

In [7]:
data_df_2024.isnull().sum()

Specie
Date                  0
Country               0
City                  0
co                38018
dew               18857
humidity           1629
neph             101856
no2               20465
o3                21114
pm10              17223
pm25              10041
precipitation     84216
pressure           1325
so2               33676
temperature        1483
uvi               98902
wd                95138
wind-gust         46109
wind-speed         2769
dtype: int64

# 2023_Q1

In [8]:
# Loading the data
raw_data_2023_Q1 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2023Q1.csv")

# print the shape
print(raw_data_2023_Q1.shape)

#runs the first 5 rows
raw_data_2023_Q1.head(10)

(553335, 5)

        Date Country    City       Specie     max
0   4/1/2023      BH  Manama     pressure  1016.2
1   4/2/2023      BH  Manama     pressure  1017.4
2  3/27/2023      BH  Manama     pressure  1012.1
3  3/28/2023      BH  Manama     pressure  1015.2
4  3/29/2023      BH  Manama     pressure  1016.1
5  3/30/2023      BH  Manama     pressure  1014.4
6  3/31/2023      BH  Manama     pressure  1010.5
7   4/2/2023      BH  Manama         pm25    38.0
8  3/27/2023      BH  Manama  temperature    25.8
9  3/28/2023      BH  Manama  temperature    26.6

In [9]:
# Convert 'Date' to datetime
raw_data_2023_Q1['Date'] = pd.to_datetime(raw_data_2023_Q1['Date'])

In [10]:
raw_data_2023_Q1.shape

(553335, 5)

In [11]:
# Pivot the data
data_df_2023_Q1 = raw_data_2023_Q1.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [12]:
print(data_df_2023_Q1.shape)
data_df_2023_Q1.head()

(54535, 22)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,neph,no2,...,pm10,pm25,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2022-12-26,AE,Abu Dhabi,NaN,0.1,19.0,93.0,NaN,NaN,34.2,...,65.0,117.0,NaN,1019.0,14.2,24.2,NaN,NaN,5.0,7.2
1,2022-12-26,AE,Dubai,NaN,NaN,17.3,91.3,NaN,NaN,NaN,...,NaN,173.0,NaN,1019.0,NaN,24.0,NaN,NaN,NaN,5.1
2,2022-12-26,AR,Buenos Aires,NaN,8.9,14.8,97.4,NaN,NaN,8.3,...,47.0,NaN,NaN,1016.6,14.2,29.1,NaN,337.5,8.2,3.0
3,2022-12-26,AT,Graz,NaN,0.1,3.4,93.7,NaN,NaN,27.5,...,67.0,114.0,NaN,1020.8,7.6,10.8,NaN,NaN,NaN,3.0
4,2022-12-26,AT,Innsbruck,NaN,0.1,4.5,100.0,NaN,NaN,18.3,...,24.0,NaN,NaN,1022.0,0.6,10.0,NaN,NaN,14.0,13.0

In [13]:
data_df_2023_Q1.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              53716
co               20563
dew              10232
humidity           192
mepaqi           54437
neph             54339
no2               9381
o3               12986
pm1              54255
pm10              9970
pm25              6880
precipitation    48004
pressure           324
so2              16332
temperature        106
uvi              53557
wd               50771
wind-gust        25751
wind-speed        1034
dtype: int64

# 2023_Q2

In [14]:
# Loading the data
raw_data_2023_Q2 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2023Q2.csv")

# print the shape
print(raw_data_2023_Q2.shape)

#runs the first 5 rows
raw_data_2023_Q2.head(10)

(564703, 5)

        Date Country     City    Specie     max
0   4/4/2023      DZ  Algiers  pressure  1018.0
1  4/25/2023      DZ  Algiers  pressure  1017.0
2  5/25/2023      DZ  Algiers  pressure  1017.0
3  3/27/2023      DZ  Algiers  pressure  1023.0
4  3/31/2023      DZ  Algiers  pressure  1024.0
5  4/14/2023      DZ  Algiers  pressure  1019.0
6  4/30/2023      DZ  Algiers  pressure  1017.0
7  5/18/2023      DZ  Algiers  pressure  1016.0
8  6/11/2023      DZ  Algiers  pressure  1016.0
9  6/24/2023      DZ  Algiers  pressure  1019.0

In [15]:
# Convert 'Date' to datetime
raw_data_2023_Q2['Date'] = pd.to_datetime(raw_data_2023_Q2['Date'])

In [16]:
raw_data_2023_Q2.shape

(564703, 5)

In [17]:
# Pivot the data
data_df_2023_Q2 = raw_data_2023_Q2.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [18]:
print(data_df_2023_Q2.shape)
data_df_2023_Q2.head()

(55730, 22)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,neph,no2,...,pm10,pm25,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2023-03-27,AE,Abu Dhabi,NaN,0.1,21.0,73.0,NaN,NaN,32.0,...,290.0,200.0,NaN,1013.4,14.3,33.0,NaN,NaN,13.8,10.2
1,2023-03-27,AE,Dubai,NaN,NaN,17.0,61.0,NaN,NaN,NaN,...,NaN,169.0,NaN,1011.0,NaN,33.0,NaN,NaN,NaN,6.6
2,2023-03-27,AR,Buenos Aires,NaN,5.6,14.3,100.0,NaN,NaN,21.1,...,30.0,NaN,NaN,1019.4,12.7,26.1,NaN,157.5,11.9,5.6
3,2023-03-27,AT,Graz,NaN,0.1,5.5,90.8,NaN,NaN,26.6,...,39.0,21.0,0.5,1014.0,2.6,12.3,NaN,NaN,NaN,8.0
4,2023-03-27,AT,Innsbruck,NaN,0.1,3.8,91.9,NaN,NaN,15.6,...,15.0,NaN,99.4,1014.9,1.6,5.3,NaN,NaN,18.4,11.0

In [19]:
data_df_2023_Q2.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              54358
co               21724
dew              11112
humidity           206
mepaqi           55632
neph             55534
no2               9257
o3               12462
pm1              55479
pm10             10038
pm25              7057
precipitation    49911
pressure           391
so2              17226
temperature        150
uvi              54759
wd               51871
wind-gust        25758
wind-speed        1242
dtype: int64

# 2023_Q3

In [20]:
# Loading the data
raw_data_2023_Q3 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2023Q3.csv")

# print the shape
print(raw_data_2023_Q3.shape)

#runs the first 5 rows
raw_data_2023_Q3.head(10)

(255419, 5)

        Date Country      City Specie   max
0  7/20/2023      JP  Kumamoto    so2   2.9
1  8/12/2023      JP  Kumamoto    so2  56.9
2  8/23/2023      JP  Kumamoto    so2  56.9
3  8/25/2023      JP  Kumamoto    so2   8.6
4  9/13/2023      JP  Kumamoto    so2   4.3
5  9/11/2023      JP  Kumamoto    so2   5.8
6  6/30/2023      JP  Kumamoto    so2   1.5
7   7/1/2023      JP  Kumamoto    so2   1.5
8   7/2/2023      JP  Kumamoto    so2   1.5
9   7/5/2023      JP  Kumamoto    so2   2.9

In [21]:
# Convert 'Date' to datetime
raw_data_2023_Q3['Date'] = pd.to_datetime(raw_data_2023_Q3['Date'])

In [22]:
raw_data_2023_Q3.shape

(255419, 5)

In [23]:
# Pivot the data
data_df_2023_Q3 = raw_data_2023_Q3.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [24]:
print(data_df_2023_Q3.shape)
data_df_2023_Q3.head()

(25197, 21)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,neph,no2,...,pm1,pm10,pm25,precipitation,pressure,so2,temperature,wd,wind-gust,wind-speed
0,2023-06-26,AE,Abu Dhabi,NaN,0.1,26.0,79.0,NaN,NaN,19.2,...,NaN,136.0,178.0,NaN,997.0,50.5,40.0,NaN,NaN,7.2
1,2023-06-26,AE,Dubai,NaN,NaN,29.0,79.0,NaN,NaN,NaN,...,NaN,NaN,132.0,NaN,997.0,NaN,39.5,NaN,NaN,6.6
2,2023-06-26,AR,Buenos Aires,NaN,12.2,14.3,100.0,NaN,NaN,17.0,...,NaN,59.0,144.0,NaN,1014.9,14.7,19.9,292.5,2.4,5.1
3,2023-06-26,AU,Adelaide,NaN,3.9,11.6,92.9,NaN,NaN,15.1,...,NaN,41.0,57.0,0.3,1020.3,NaN,16.5,NaN,13.1,7.2
4,2023-06-26,AU,Brisbane,NaN,3.1,8.7,83.6,NaN,NaN,16.5,...,NaN,90.0,71.0,NaN,1020.2,3.1,24.4,326.0,20.5,7.7

In [25]:
data_df_2023_Q3.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              25102
co               10340
dew               5166
humidity            23
mepaqi           25099
neph             25001
no2               4438
o3                3734
pm1              25100
pm10              5937
pm25              2644
precipitation    21924
pressure           169
so2               8920
temperature          2
wd               24217
wind-gust         9754
wind-speed         557
dtype: int64

# 2023_Q4

In [26]:
# Loading the data
raw_data_2023_Q4 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2023Q4.csv")

# print the shape
print(raw_data_2023_Q4.shape)

#runs the first 5 rows
raw_data_2023_Q4.head(10)

(217731, 5)

         Date Country   City    Specie     max
0  10/30/2023      FI  Turku  pressure  1005.0
1   11/9/2023      FI  Turku  pressure  1005.0
2  11/26/2023      FI  Turku  pressure  1009.5
3   12/6/2023      FI  Turku  pressure  1027.0
4  12/12/2023      FI  Turku  pressure  1009.0
5  12/13/2023      FI  Turku  pressure  1010.0
6  12/30/2023      FI  Turku  pressure  1006.5
7   10/8/2023      FI  Turku  pressure  1013.0
8  11/10/2023      FI  Turku  pressure  1002.5
9  11/22/2023      FI  Turku  pressure  1027.5

In [27]:
# Convert 'Date' to datetime
raw_data_2023_Q4['Date'] = pd.to_datetime(raw_data_2023_Q4['Date'])

In [28]:
raw_data_2023_Q4.shape

(217731, 5)

In [29]:
# Pivot the data
data_df_2023_Q4 = raw_data_2023_Q4.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [30]:
print(data_df_2023_Q4.shape)
data_df_2023_Q4.head()

(22632, 21)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,no2,o3,...,pm10,pm25,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2023-09-25,AT,Graz,NaN,0.1,14.0,100.0,NaN,18.8,NaN,...,37.0,55.0,NaN,1026.0,1.1,18.6,NaN,NaN,9.6,4.3
1,2023-09-25,AT,Innsbruck,NaN,0.1,NaN,58.0,NaN,20.6,NaN,...,29.0,NaN,NaN,1022.1,1.8,26.6,NaN,NaN,6.0,2.0
2,2023-09-25,AT,Linz,NaN,0.1,13.0,93.0,NaN,22.9,NaN,...,22.0,56.0,NaN,1027.0,3.1,22.8,NaN,NaN,8.0,6.1
3,2023-09-25,AT,Salzburg,NaN,0.1,13.0,100.0,NaN,28.4,NaN,...,17.0,38.0,NaN,1026.0,1.6,20.0,NaN,NaN,NaN,3.0
4,2023-09-25,AT,Vienna,NaN,0.1,14.0,89.1,NaN,33.9,NaN,...,50.0,59.0,NaN,1032.5,2.6,23.8,NaN,NaN,22.2,10.0

In [31]:
data_df_2023_Q4.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              21358
co               11602
dew               4359
humidity            65
mepaqi           22534
no2               5375
o3                7954
pm1              22372
pm10              5288
pm25              5839
precipitation    19716
pressure           201
so2               8084
temperature         32
uvi              21841
wd               21683
wind-gust        11027
wind-speed         315
dtype: int64

# 2022_Q2

In [32]:
# Loading the data
raw_data_2022_Q2 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2022Q2.csv")

# print the shape
print(raw_data_2022_Q2.shape)

#runs the first 5 rows
raw_data_2022_Q2.head(10)

(573836, 5)

        Date Country            City    Specie     max
0  3/31/2022      GT  Guatemala City  pressure  1020.0
1  4/23/2022      GT  Guatemala City  pressure  1023.0
2   5/6/2022      GT  Guatemala City  pressure  1023.0
3  6/10/2022      GT  Guatemala City  pressure  1022.0
4   4/4/2022      GT  Guatemala City  pressure  1020.0
5  5/13/2022      GT  Guatemala City  pressure  1022.0
6   6/3/2022      GT  Guatemala City  pressure  1019.0
7   6/9/2022      GT  Guatemala City  pressure  1022.0
8   6/2/2022      GT  Guatemala City  pressure  1019.0
9  6/30/2022      GT  Guatemala City  pressure  1025.0

In [33]:
# Convert 'Date' to datetime
raw_data_2022_Q2['Date'] = pd.to_datetime(raw_data_2022_Q2['Date'])

In [34]:
raw_data_2022_Q2.shape

(573836, 5)

In [35]:
# Pivot the data
data_df_2022_Q2 = raw_data_2022_Q2.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [36]:
print(data_df_2022_Q2.shape)
data_df_2022_Q2.head()

(56751, 22)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,neph,no2,...,pm10,pm25,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2022-03-28,AE,Abu Dhabi,NaN,0.1,16.0,73.3,NaN,NaN,10.9,...,93.0,61.0,NaN,1019.2,41.3,25.1,NaN,NaN,6.3,8.7
1,2022-03-28,AE,Dubai,NaN,NaN,17.0,68.0,NaN,NaN,NaN,...,NaN,80.0,NaN,1017.0,NaN,26.0,NaN,NaN,NaN,7.7
2,2022-03-28,AR,Buenos Aires,NaN,0.1,17.7,89.0,NaN,NaN,NaN,...,35.0,95.0,NaN,1024.7,64.8,27.3,NaN,337.5,13.4,5.1
3,2022-03-28,AT,Graz,NaN,0.1,3.9,80.8,NaN,NaN,48.0,...,137.0,NaN,NaN,1026.8,13.7,22.7,NaN,NaN,10.5,5.5
4,2022-03-28,AT,Innsbruck,NaN,0.1,-0.5,77.0,NaN,NaN,38.0,...,59.0,NaN,99.0,1027.0,1.1,22.0,NaN,NaN,9.5,8.0

In [37]:
data_df_2022_Q2.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              55322
co               20880
dew              12576
humidity            86
mepaqi           56653
neph             56555
no2              10984
o3               14660
pm1              56486
pm10              9916
pm25              7691
precipitation    50204
pressure           358
so2              18493
temperature         69
uvi              55772
wd               52418
wind-gust        24603
wind-speed         707
dtype: int64

# 2022_Q3

In [38]:
# Loading the data
raw_data_2022_Q3 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2022Q3.csv")

# print the shape
print(raw_data_2022_Q3.shape)

#runs the first 5 rows
raw_data_2022_Q3.head(10)

(570466, 5)

        Date Country         City      Specie  max
0  7/14/2022      MX  Guadalajara  wind-speed  7.7
1   8/6/2022      MX  Guadalajara  wind-speed  6.0
2  8/25/2022      MX  Guadalajara  wind-speed  2.5
3  8/29/2022      MX  Guadalajara  wind-speed  3.0
4  8/31/2022      MX  Guadalajara  wind-speed  4.6
5   9/5/2022      MX  Guadalajara  wind-speed  5.6
6  6/30/2022      MX  Guadalajara  wind-speed  6.1
7  7/30/2022      MX  Guadalajara  wind-speed  7.8
8   8/9/2022      MX  Guadalajara  wind-speed  6.1
9  8/15/2022      MX  Guadalajara  wind-speed  6.6

In [39]:
# Convert 'Date' to datetime
raw_data_2022_Q3['Date'] = pd.to_datetime(raw_data_2022_Q3['Date'])

In [40]:
raw_data_2022_Q3.shape

(570466, 5)

In [41]:
# Pivot the data
data_df_2022_Q3 = raw_data_2022_Q3.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [42]:
print(data_df_2022_Q3.shape)
data_df_2022_Q3.head()

(56219, 22)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,neph,no2,...,pm10,pm25,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2022-06-27,AE,Abu Dhabi,NaN,0.1,29.0,84.0,NaN,NaN,35.4,...,197.0,287.0,NaN,998.6,9.5,38.5,NaN,NaN,2.8,8.7
1,2022-06-27,AE,Dubai,NaN,NaN,29.0,75.0,NaN,NaN,NaN,...,NaN,302.0,NaN,997.0,NaN,41.0,NaN,NaN,NaN,7.2
2,2022-06-27,AR,Buenos Aires,NaN,13.2,7.3,86.0,NaN,NaN,NaN,...,62.0,159.0,NaN,1029.7,12.7,12.5,NaN,337.5,6.9,3.6
3,2022-06-27,AT,Graz,NaN,0.1,20.3,85.8,NaN,NaN,54.1,...,132.0,50.0,NaN,1017.7,3.1,32.5,NaN,NaN,12.5,5.8
4,2022-06-27,AT,Innsbruck,NaN,0.1,18.0,77.0,NaN,NaN,26.6,...,65.0,NaN,NaN,1019.5,0.6,33.5,NaN,NaN,20.5,7.4

In [43]:
data_df_2022_Q3.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              54757
co               20304
dew              12264
humidity            85
mepaqi           56121
neph             56023
no2              10326
o3               13608
pm1              56023
pm10              9727
pm25              7383
precipitation    48775
pressure           337
so2              18086
temperature         45
uvi              55241
wd               52204
wind-gust        25319
wind-speed        1067
dtype: int64

# 2022_Q4

In [44]:
# Loading the data
raw_data_2022_Q4 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2022Q4.csv")

# print the shape
print(raw_data_2022_Q4.shape)

#runs the first 5 rows
raw_data_2022_Q4.head(10)

(551341, 5)

         Date Country       City    Specie    max
0  10/20/2022      GB  Edinburgh  humidity  100.0
1   11/2/2022      GB  Edinburgh  humidity   96.5
2   11/8/2022      GB  Edinburgh  humidity   90.8
3  11/13/2022      GB  Edinburgh  humidity   99.0
4  11/19/2022      GB  Edinburgh  humidity  100.0
5  11/20/2022      GB  Edinburgh  humidity   96.5
6   12/4/2022      GB  Edinburgh  humidity  100.0
7   12/6/2022      GB  Edinburgh  humidity   96.5
8  12/13/2022      GB  Edinburgh  humidity   96.0
9  12/15/2022      GB  Edinburgh  humidity   92.0

In [45]:
# Convert 'Date' to datetime
raw_data_2022_Q4['Date'] = pd.to_datetime(raw_data_2022_Q4['Date'])

In [46]:
raw_data_2022_Q4.shape

(551341, 5)

In [47]:
# Pivot the data
data_df_2022_Q4 = raw_data_2022_Q4.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [48]:
print(data_df_2022_Q4.shape)
data_df_2022_Q4.head()

(54530, 22)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,neph,no2,...,pm10,pm25,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2022-09-26,AE,Abu Dhabi,NaN,0.1,28.0,91.0,NaN,NaN,18.4,...,145.0,NaN,NaN,1007.1,31.6,40.0,NaN,NaN,5.7,6.1
1,2022-09-26,AE,Dubai,NaN,NaN,28.0,84.0,NaN,NaN,NaN,...,NaN,198.0,NaN,1006.0,NaN,39.0,NaN,NaN,NaN,6.1
2,2022-09-26,AR,Buenos Aires,NaN,11.7,15.8,95.0,NaN,NaN,NaN,...,49.0,21.0,NaN,1015.2,11.2,24.1,NaN,157.5,NaN,4.6
3,2022-09-26,AT,Graz,NaN,0.1,11.8,97.4,NaN,NaN,26.6,...,31.0,53.0,99.3,1009.0,3.1,17.6,NaN,NaN,4.8,2.2
4,2022-09-26,AT,Innsbruck,NaN,0.1,11.1,100.0,NaN,NaN,17.4,...,17.0,NaN,99.1,1010.0,0.6,16.5,NaN,NaN,2.0,6.0

In [49]:
data_df_2022_Q4.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              53624
co               19997
dew              10675
humidity           203
mepaqi           54432
neph             54334
no2               9605
o3               12958
pm1              54282
pm10             10067
pm25              6960
precipitation    48184
pressure           395
so2              16571
temperature        103
uvi              53550
wd               50877
wind-gust        26553
wind-speed        1359
dtype: int64

# 2021_Q1

In [50]:
# Loading the data
raw_data_2021_Q1 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2021Q1.csv")

# print the shape
print(raw_data_2021_Q1.shape)

#runs the first 5 rows
raw_data_2021_Q1.head(10)

(590729, 5)

        Date Country     City    Specie     max
0   4/4/2021      CN  Beijing  pressure  1028.0
1  2/13/2021      CN  Beijing  pressure  1022.5
2  2/16/2021      CN  Beijing  pressure  1030.0
3   3/1/2021      CN  Beijing  pressure  1032.0
4  3/14/2021      CN  Beijing  pressure  1019.0
5  3/16/2021      CN  Beijing  pressure  1026.0
6   4/2/2021      CN  Beijing  pressure  1022.0
7  3/21/2021      CN  Beijing  pressure  1027.0
8   1/6/2021      CN  Beijing  pressure  1043.5
9  1/16/2021      CN  Beijing  pressure  1036.0

In [51]:
# Convert 'Date' to datetime
raw_data_2021_Q1['Date'] = pd.to_datetime(raw_data_2021_Q1['Date'])

In [52]:
raw_data_2021_Q1.shape

(590729, 5)

In [53]:
# Pivot the data
data_df_2021_Q1 = raw_data_2021_Q1.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [54]:
print(data_df_2021_Q1.shape)
data_df_2021_Q1.head()

(58552, 22)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,neph,no2,...,pm10,pm25,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2020-12-28,AE,Abu Dhabi,NaN,0.1,16.0,73.0,NaN,NaN,38.9,...,113.0,65.0,NaN,1022.0,9.2,25.0,NaN,NaN,NaN,5.6
1,2020-12-28,AE,Dubai,NaN,NaN,11.0,52.0,NaN,NaN,NaN,...,NaN,72.0,NaN,1022.0,NaN,25.0,NaN,NaN,NaN,5.6
2,2020-12-28,AF,Kabul,NaN,NaN,-10.0,68.0,NaN,NaN,NaN,...,NaN,384.0,NaN,1022.0,NaN,7.0,NaN,NaN,NaN,7.2
3,2020-12-28,AR,Buenos Aires,NaN,5.5,22.5,87.0,NaN,NaN,17.9,...,35.0,104.0,NaN,1031.5,NaN,31.9,NaN,135.0,18.3,9.7
4,2020-12-28,AT,Graz,NaN,0.1,0.1,99.0,NaN,NaN,28.4,...,31.0,NaN,99.5,997.5,1.8,2.0,NaN,NaN,4.1,2.0

In [55]:
data_df_2021_Q1.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              57095
co               21064
dew              12610
humidity           203
mepaqi           58454
neph             58356
no2              10946
o3               15009
pm1              58358
pm10             10897
pm25              8962
precipitation    52036
pressure           360
so2              18363
temperature        177
uvi              57577
wd               53821
wind-gust        26579
wind-speed         892
dtype: int64

# 2021_Q2

In [56]:
# Loading the data
raw_data_2021_Q2 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2021Q2.csv")

# print the shape
print(raw_data_2021_Q2.shape)

#runs the first 5 rows
raw_data_2021_Q2.head(10)

(587119, 5)

        Date Country     City Specie   max
0   4/8/2021      IQ  Baghdad    dew   8.5
1   7/1/2021      IQ  Baghdad    dew  14.0
2   4/6/2021      IQ  Baghdad    dew   7.0
3  4/14/2021      IQ  Baghdad    dew   4.0
4  4/19/2021      IQ  Baghdad    dew  10.0
5   5/8/2021      IQ  Baghdad    dew  13.0
6  5/17/2021      IQ  Baghdad    dew  12.0
7  5/21/2021      IQ  Baghdad    dew  11.0
8  5/22/2021      IQ  Baghdad    dew  13.0
9   6/3/2021      IQ  Baghdad    dew  10.0

In [57]:
# Convert 'Date' to datetime
raw_data_2021_Q2['Date'] = pd.to_datetime(raw_data_2021_Q2['Date'])

In [58]:
raw_data_2021_Q2.shape

(587119, 5)

In [59]:
# Pivot the data
data_df_2021_Q2 = raw_data_2021_Q2.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [60]:
print(data_df_2021_Q2.shape)
data_df_2021_Q2.head()

(58359, 22)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,neph,no2,...,pm10,pm25,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2021-03-29,AE,Abu Dhabi,NaN,0.1,18.0,73.0,NaN,NaN,14.7,...,99.0,NaN,NaN,1014.0,15.8,28.0,NaN,NaN,NaN,8.2
1,2021-03-29,AE,Dubai,NaN,NaN,19.0,78.0,NaN,NaN,NaN,...,NaN,99.0,NaN,1013.0,NaN,29.0,NaN,NaN,NaN,5.6
2,2021-03-29,AF,Kabul,NaN,NaN,7.0,87.0,NaN,NaN,NaN,...,NaN,153.0,NaN,1019.0,NaN,18.0,NaN,NaN,12.8,8.2
3,2021-03-29,AR,Buenos Aires,NaN,0.1,NaN,94.0,NaN,NaN,NaN,...,NaN,NaN,NaN,1014.9,NaN,23.2,NaN,225.0,10.6,3.4
4,2021-03-29,AT,Graz,NaN,0.1,3.4,90.8,NaN,NaN,39.4,...,60.0,NaN,NaN,1033.1,12.2,20.7,NaN,NaN,10.3,5.7

In [61]:
data_df_2021_Q2.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              57041
co               21327
dew              13091
humidity           798
mepaqi           58261
neph             58163
no2              11014
o3               14925
pm1              57970
pm10             10603
pm25              8315
precipitation    51439
pressure           951
so2              19006
temperature        776
uvi              57379
wd               54281
wind-gust        24945
wind-speed        1417
dtype: int64

# 2021_Q3

In [62]:
# Loading the data
raw_data_2021_Q3 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2021Q3.csv")

# print the shape
print(raw_data_2021_Q3.shape)

#runs the first 5 rows
raw_data_2021_Q3.head(10)

(570079, 5)

        Date Country                 City Specie   max
0   7/5/2021      BR  São José dos Campos    no2  17.9
1  7/16/2021      BR  São José dos Campos    no2  33.9
2  7/27/2021      BR  São José dos Campos    no2  34.8
3   8/3/2021      BR  São José dos Campos    no2  25.6
4  8/29/2021      BR  São José dos Campos    no2  14.2
5  9/21/2021      BR  São José dos Campos    no2  25.6
6  8/22/2021      BR  São José dos Campos    no2  33.9
7  9/11/2021      BR  São José dos Campos    no2  24.7
8   7/2/2021      BR  São José dos Campos    no2  41.6
9   7/7/2021      BR  São José dos Campos    no2  25.6

In [63]:
# Convert 'Date' to datetime
raw_data_2021_Q3['Date'] = pd.to_datetime(raw_data_2021_Q3['Date'])

In [64]:
raw_data_2021_Q3.shape

(570079, 5)

In [65]:
# Pivot the data
data_df_2021_Q3 = raw_data_2021_Q3.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [66]:
print(data_df_2021_Q3.shape)
data_df_2021_Q3.head()

(57529, 22)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,neph,no2,...,pm10,pm25,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2021-06-28,AE,Abu Dhabi,NaN,0.1,27.0,63.0,NaN,NaN,36.2,...,374.0,336.0,NaN,1005.0,13.7,43.0,NaN,NaN,NaN,8.2
1,2021-06-28,AE,Dubai,NaN,NaN,24.0,56.0,NaN,NaN,NaN,...,NaN,NaN,NaN,1005.0,NaN,41.0,NaN,NaN,NaN,7.2
2,2021-06-28,AF,Kabul,NaN,NaN,8.0,62.0,NaN,NaN,NaN,...,NaN,427.0,NaN,1020.0,NaN,32.0,NaN,NaN,11.3,9.2
3,2021-06-28,AR,Buenos Aires,NaN,2.9,4.2,91.0,NaN,NaN,10.6,...,16.0,57.0,99.0,1040.3,2.6,9.2,NaN,270.0,16.3,6.4
4,2021-06-28,AT,Graz,NaN,0.1,16.6,84.0,NaN,NaN,34.8,...,90.0,NaN,99.0,1018.2,4.6,33.0,NaN,NaN,13.6,7.6

In [67]:
data_df_2021_Q3.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              56333
co               21042
dew              12891
humidity          2237
mepaqi           57432
neph             57333
no2              10657
o3               14558
pm1              57173
pm10             10242
pm25              8362
precipitation    51411
pressure          2320
so2              18480
temperature       2216
uvi              56561
wd               54784
wind-gust        26014
wind-speed        2926
dtype: int64

# 2021_Q4

In [68]:
# Loading the data
raw_data_2021_Q4 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2021Q4.csv")

# print the shape
print(raw_data_2021_Q4.shape)

#runs the first 5 rows
raw_data_2021_Q4.head(10)

(548423, 5)

         Date Country    City    Specie     max
0  10/24/2021      BH  Manama  pressure  1013.0
1  11/12/2021      BH  Manama  pressure  1015.3
2  11/27/2021      BH  Manama  pressure  1017.3
3  12/10/2021      BH  Manama  pressure  1022.7
4  12/22/2021      BH  Manama  pressure  1020.1
5  12/26/2021      BH  Manama  pressure  1021.7
6  10/11/2021      BH  Manama  pressure  1008.7
7  10/18/2021      BH  Manama  pressure  1010.6
8  11/15/2021      BH  Manama  pressure  1016.1
9  11/16/2021      BH  Manama  pressure  1012.4

In [69]:
# Convert 'Date' to datetime
raw_data_2021_Q4['Date'] = pd.to_datetime(raw_data_2021_Q4['Date'])

In [70]:
raw_data_2021_Q4.shape

(548423, 5)

In [71]:
# Pivot the data
data_df_2021_Q4 = raw_data_2021_Q4.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [72]:
print(data_df_2021_Q4.shape)
data_df_2021_Q4.head()

(57596, 22)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,neph,no2,...,pm10,pm25,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2021-09-27,AE,Abu Dhabi,NaN,0.1,24.0,62.0,NaN,NaN,34.8,...,157.0,233.0,NaN,1005.0,9.7,36.0,NaN,NaN,NaN,6.6
1,2021-09-27,AE,Dubai,NaN,NaN,25.0,70.0,NaN,NaN,NaN,...,NaN,162.0,NaN,1005.0,NaN,37.0,NaN,NaN,NaN,6.6
2,2021-09-27,AR,Buenos Aires,NaN,7.5,13.9,95.8,NaN,NaN,10.6,...,28.0,68.0,NaN,1020.0,NaN,16.4,NaN,NaN,12.2,9.7
3,2021-09-27,AT,Graz,NaN,0.1,16.0,99.0,NaN,NaN,32.5,...,40.0,NaN,0.3,1018.3,2.6,21.2,NaN,NaN,7.5,3.7
4,2021-09-27,AT,Innsbruck,NaN,0.1,14.3,100.0,NaN,NaN,25.2,...,26.0,NaN,0.7,1021.0,1.1,21.7,NaN,NaN,11.7,8.0

In [73]:
data_df_2021_Q4.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              56254
co               21421
dew              15917
humidity          5137
mepaqi           57498
neph             57400
no2              11193
o3               15551
pm1              57213
pm10             10535
pm25              9407
precipitation    52472
pressure          4971
so2              19425
temperature       4923
uvi              56620
wd               55617
wind-gust        28316
wind-speed        6031
dtype: int64

# 2020_Q1

In [74]:
# Loading the data
raw_data_2020_Q1 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2020Q1.csv")

# print the shape
print(raw_data_2020_Q1.shape)

#runs the first 5 rows
raw_data_2020_Q1.head(10)

(539573, 5)

        Date Country    City Specie   max
0  1/13/2020      CO  Bogotá    so2   2.8
1  2/25/2020      CO  Bogotá    so2   4.1
2   3/9/2020      CO  Bogotá    so2   5.4
3  3/13/2020      CO  Bogotá    so2   3.7
4  3/27/2020      CO  Bogotá    so2  13.8
5   4/5/2020      CO  Bogotá    so2   2.5
6   1/1/2020      CO  Bogotá    so2   2.5
7  1/10/2020      CO  Bogotá    so2   8.8
8  2/27/2020      CO  Bogotá    so2   3.4
9   3/8/2020      CO  Bogotá    so2   2.6

In [75]:
# Convert 'Date' to datetime
raw_data_2020_Q1['Date'] = pd.to_datetime(raw_data_2020_Q1['Date'])

In [76]:
raw_data_2020_Q1.shape

(539573, 5)

In [77]:
# Pivot the data
data_df_2020_Q1 = raw_data_2020_Q1.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [78]:
print(data_df_2020_Q1.shape)
data_df_2020_Q1.head()

(59069, 25)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,neph,no2,...,precipitation,pressure,so2,temperature,uvi,wd,wind gust,wind speed,wind-gust,wind-speed
0,2019-12-30,AE,Abu Dhabi,NaN,0.1,NaN,NaN,NaN,NaN,50.4,...,NaN,NaN,14.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-12-30,AE,Dubai,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-12-30,AF,Kabul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-12-30,AR,Buenos Aires,NaN,11.0,NaN,NaN,NaN,NaN,17.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-12-30,AT,Graz,NaN,0.1,NaN,NaN,NaN,NaN,32.0,...,NaN,NaN,3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [79]:
data_df_2020_Q1.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              57661
co               22080
dew              22910
humidity         11489
mepaqi           58971
neph             58873
no2              11017
o3               14542
pm1              58687
pm10             10818
pm25              9623
pol              58354
precipitation    55234
pressure         11631
so2              18847
temperature      11481
uvi              58086
wd               55488
wind gust        30802
wind speed       14994
wind-gust        55472
wind-speed       52885
dtype: int64

# 2020_Q2

In [80]:
# Loading the data
raw_data_2020_Q2 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2020Q2.csv")

# print the shape
print(raw_data_2020_Q2.shape)

#runs the first 5 rows
raw_data_2020_Q2.head(10)

(602520, 5)

        Date Country      City      Specie   max
0  4/15/2020      IN  Thrissur   wind-gust  10.2
1  4/26/2020      IN  Thrissur   wind-gust  12.8
2   5/2/2020      IN  Thrissur   wind-gust   8.7
3  5/11/2020      IN  Thrissur   wind-gust  11.3
4  6/21/2020      IN  Thrissur   wind-gust  10.2
5   7/2/2020      IN  Thrissur   wind-gust  11.8
6  3/30/2020      IN  Thrissur  wind speed   6.1
7  3/31/2020      IN  Thrissur  wind speed   6.1
8  5/31/2020      IN  Thrissur          o3   5.8
9   4/8/2020      IN  Thrissur          o3  17.1

In [81]:
# Convert 'Date' to datetime
raw_data_2020_Q2['Date'] = pd.to_datetime(raw_data_2020_Q2['Date'])

In [82]:
raw_data_2020_Q2.shape

(602520, 5)

In [83]:
# Pivot the data
data_df_2020_Q2 = raw_data_2020_Q2.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [84]:
print(data_df_2020_Q2.shape)
data_df_2020_Q1.head()

(59500, 24)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,neph,no2,...,precipitation,pressure,so2,temperature,uvi,wd,wind gust,wind speed,wind-gust,wind-speed
0,2019-12-30,AE,Abu Dhabi,NaN,0.1,NaN,NaN,NaN,NaN,50.4,...,NaN,NaN,14.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019-12-30,AE,Dubai,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019-12-30,AF,Kabul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019-12-30,AR,Buenos Aires,NaN,11.0,NaN,NaN,NaN,NaN,17.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019-12-30,AT,Graz,NaN,0.1,NaN,NaN,NaN,NaN,32.0,...,NaN,NaN,3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
data_df_2020_Q2.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              58118
co               22434
dew              12453
humidity            84
mepaqi           59402
neph             59304
no2              11349
o3               14440
pm1              59138
pm10             11078
pm25              9389
precipitation    52038
pressure           309
so2              18997
temperature         71
uvi              58494
wd               55060
wind gust        58877
wind speed       58341
wind-gust        26841
wind-speed         763
dtype: int64

# 2020_Q3

In [86]:
# Loading the data
raw_data_2020_Q3 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2020Q3.csv")

# print the shape
print(raw_data_2020_Q3.shape)

#runs the first 5 rows
raw_data_2020_Q3.head(10)

(598100, 5)

        Date Country    City Specie   max
0  8/16/2020      UA  Odessa   pm10  13.0
1  8/18/2020      UA  Odessa   pm10   9.0
2  8/24/2020      UA  Odessa   pm10   8.0
3  8/25/2020      UA  Odessa   pm10  12.0
4  8/26/2020      UA  Odessa   pm10   7.0
5  8/28/2020      UA  Odessa   pm10  14.0
6  8/13/2020      UA  Odessa   pm10  12.0
7  8/14/2020      UA  Odessa   pm10   9.0
8  8/19/2020      UA  Odessa   pm10  12.0
9  8/27/2020      UA  Odessa   pm10  11.0

In [87]:
# Convert 'Date' to datetime
raw_data_2020_Q3['Date'] = pd.to_datetime(raw_data_2020_Q3['Date'])

In [88]:
raw_data_2020_Q3.shape

(598100, 5)

In [89]:
# Pivot the data
data_df_2020_Q3 = raw_data_2020_Q3.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [90]:
print(data_df_2020_Q3.shape)
data_df_2020_Q3.head()

(59172, 22)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,neph,no2,...,pm10,pm25,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2020-06-29,AE,Abu Dhabi,NaN,0.1,28.0,89.0,NaN,NaN,29.8,...,223.0,129.0,NaN,998.0,17.8,43.0,NaN,NaN,NaN,7.7
1,2020-06-29,AE,Dubai,NaN,NaN,28.0,75.0,NaN,NaN,NaN,...,NaN,165.0,NaN,998.0,NaN,41.0,NaN,NaN,NaN,7.2
2,2020-06-29,AF,Kabul,NaN,NaN,10.0,43.0,NaN,NaN,NaN,...,NaN,112.0,NaN,1015.0,NaN,31.0,NaN,NaN,13.8,8.7
3,2020-06-29,AR,Buenos Aires,NaN,10.0,10.8,98.7,NaN,NaN,31.6,...,17.0,30.0,NaN,1022.4,0.6,13.3,NaN,112.5,19.6,10.2
4,2020-06-29,AT,Graz,NaN,0.1,18.7,96.6,NaN,NaN,22.9,...,39.0,NaN,99.0,1015.0,5.6,26.8,NaN,NaN,21.0,6.2

In [91]:
data_df_2020_Q3.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              57689
co               22203
dew              12016
humidity            87
mepaqi           59074
neph             58976
no2              11175
o3               13982
pm1              58848
pm10             10889
pm25              9314
precipitation    51268
pressure           426
so2              18642
temperature        106
uvi              58291
wd               54519
wind-gust        27905
wind-speed         758
dtype: int64

# 2020_Q4

In [92]:
# Loading the data
raw_data_2020_Q4 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2020Q4.csv")

# print the shape
print(raw_data_2020_Q4.shape)

#runs the first 5 rows
raw_data_2020_Q4.head(10)

(586937, 5)

         Date Country         City Specie    max
0  12/23/2020      ET  Addis Ababa   pm25  167.0
1  10/12/2020      ET  Addis Ababa   pm25  119.0
2  10/17/2020      ET  Addis Ababa   pm25  153.0
3  11/25/2020      ET  Addis Ababa   pm25  137.0
4  11/27/2020      ET  Addis Ababa   pm25   82.0
5   12/9/2020      ET  Addis Ababa   pm25   80.0
6  10/25/2020      ET  Addis Ababa   pm25   85.0
7  10/31/2020      ET  Addis Ababa   pm25  129.0
8  10/18/2020      ET  Addis Ababa   pm25  153.0
9   11/8/2020      ET  Addis Ababa   pm25  157.0

In [93]:
# Convert 'Date' to datetime
raw_data_2020_Q4['Date'] = pd.to_datetime(raw_data_2020_Q4['Date'])

In [94]:
raw_data_2020_Q4.shape

(586937, 5)

In [95]:
# Pivot the data
data_df_2020_Q4 = raw_data_2020_Q4.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [96]:
print(data_df_2020_Q4.shape)
data_df_2020_Q4.head()

(58362, 22)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,neph,no2,...,pm10,pm25,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2020-09-28,AE,Abu Dhabi,NaN,0.1,28.0,89.0,NaN,NaN,29.3,...,76.0,95.0,NaN,1007.0,12.2,41.0,NaN,NaN,NaN,6.1
1,2020-09-28,AE,Dubai,NaN,NaN,27.0,83.0,NaN,NaN,NaN,...,NaN,117.0,NaN,1007.0,NaN,40.0,NaN,NaN,NaN,5.6
2,2020-09-28,AF,Kabul,NaN,NaN,8.0,66.0,NaN,NaN,NaN,...,NaN,147.0,NaN,1021.0,NaN,27.0,NaN,NaN,NaN,6.6
3,2020-09-28,AR,Buenos Aires,NaN,10.8,11.1,91.0,NaN,NaN,23.8,...,29.0,65.0,NaN,1029.7,1.6,22.8,NaN,337.5,11.7,4.8
4,2020-09-28,AT,Graz,NaN,0.1,9.8,99.0,NaN,NaN,27.5,...,22.0,NaN,1.4,1013.0,3.1,12.2,NaN,NaN,10.0,3.5

In [97]:
data_df_2020_Q4.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              56864
co               21639
dew              11928
humidity           150
mepaqi           58264
neph             58166
no2              10851
o3               14731
pm1              58017
pm10             10882
pm25              8929
precipitation    52342
pressure           356
so2              18883
temperature        113
uvi              57392
wd               53565
wind-gust        27934
wind-speed         935
dtype: int64

# 2019_Q1

In [98]:
# Loading the data
raw_data_2019_Q1 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2019Q1.csv")

# print the shape
print(raw_data_2019_Q1.shape)

#runs the first 5 rows
raw_data_2019_Q1.head(10)

(491161, 5)

        Date Country       City Specie    max
0  1/16/2019      AE  Abu Dhabi   pm10   99.0
1  1/22/2019      AE  Abu Dhabi   pm10   57.0
2  1/26/2019      AE  Abu Dhabi   pm10  173.0
3   1/7/2019      AE  Abu Dhabi   pm10   91.0
4  1/10/2019      AE  Abu Dhabi   pm10   93.0
5  1/14/2019      AE  Abu Dhabi   pm10   76.0
6  1/15/2019      AE  Abu Dhabi   pm10   97.0
7  1/21/2019      AE  Abu Dhabi   pm10   59.0
8   1/8/2019      AE  Abu Dhabi   pm10   98.0
9  1/17/2019      AE  Abu Dhabi   pm10   85.0

In [99]:
# Convert 'Date' to datetime
raw_data_2019_Q1['Date'] = pd.to_datetime(raw_data_2019_Q1['Date'])

In [100]:
raw_data_2019_Q1.shape

(491161, 5)

In [101]:
# Pivot the data
data_df_2019_Q1 = raw_data_2019_Q1.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [102]:
print(data_df_2019_Q1.shape)
data_df_2019_Q1.head()

(49006, 22)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,no2,o3,...,pm25,pol,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2018-12-31,AE,Abu Dhabi,NaN,NaN,19.0,94.0,NaN,49.4,56.5,...,152.0,NaN,NaN,1021.0,27.9,27.0,NaN,NaN,NaN,6.1
1,2018-12-31,AR,Buenos Aires,NaN,NaN,21.0,78.0,NaN,NaN,NaN,...,NaN,NaN,NaN,1011.0,NaN,23.8,NaN,0.0,188.2,17.3
2,2018-12-31,AT,Graz,NaN,0.1,NaN,82.0,NaN,35.2,NaN,...,NaN,NaN,NaN,1043.7,2.6,9.0,NaN,NaN,8.6,4.5
3,2018-12-31,AT,Innsbruck,NaN,0.1,0.5,100.0,NaN,42.5,NaN,...,NaN,NaN,NaN,1034.5,1.8,2.2,NaN,NaN,23.3,11.3
4,2018-12-31,AT,Linz,NaN,0.1,3.0,100.0,NaN,18.3,NaN,...,82.0,NaN,NaN,1036.9,17.3,5.1,NaN,NaN,11.7,6.9

In [103]:
data_df_2019_Q1.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              47701
co               17145
dew              21593
humidity           293
mepaqi           48915
no2               7765
o3                9237
pm1              48915
pm10              9686
pm25              7771
pol              48812
precipitation    45579
pressure           526
so2              13818
temperature        280
uvi              48084
wd               43626
wind-gust        16846
wind-speed        3361
dtype: int64

# 2019_Q2

In [104]:
# Loading the data
raw_data_2019_Q2 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2019Q2.csv")

# print the shape
print(raw_data_2019_Q2.shape)

#runs the first 5 rows
raw_data_2019_Q2.head(10)

(522904, 5)

        Date Country   City Specie   max
0  5/10/2019      MO  Macau     o3  42.9
1  5/14/2019      MO  Macau     o3  39.4
2  5/15/2019      MO  Macau     o3  24.1
3  5/22/2019      MO  Macau     o3  70.9
4  5/29/2019      MO  Macau     o3  42.0
5  4/19/2019      MO  Macau     o3  40.7
6  4/22/2019      MO  Macau     o3  32.2
7  4/24/2019      MO  Macau     o3  27.3
8   5/7/2019      MO  Macau     o3  44.9
9   6/4/2019      MO  Macau     o3  26.7

In [105]:
# Convert 'Date' to datetime
raw_data_2019_Q2['Date'] = pd.to_datetime(raw_data_2019_Q2['Date'])

In [106]:
raw_data_2019_Q2.shape

(522904, 5)

In [107]:
# Pivot the data
data_df_2019_Q2 = raw_data_2019_Q2.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [108]:
print(data_df_2019_Q2.shape)
data_df_2019_Q2.head()

(51421, 22)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,no2,o3,...,pm25,pol,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2019-04-01,AE,Abu Dhabi,NaN,NaN,14.0,39.0,NaN,NaN,NaN,...,175.0,NaN,NaN,1011.0,NaN,40.0,NaN,NaN,NaN,9.2
1,2019-04-01,AE,Dubai,NaN,NaN,12.0,28.0,NaN,NaN,15.9,...,160.0,NaN,NaN,1012.0,NaN,38.5,NaN,NaN,NaN,7.2
2,2019-04-01,AR,Buenos Aires,NaN,NaN,21.0,94.0,NaN,NaN,14.7,...,70.0,NaN,NaN,1016.0,2.6,27.8,NaN,0.0,9.9,4.6
3,2019-04-01,AT,Graz,NaN,0.1,NaN,90.7,NaN,43.5,NaN,...,NaN,NaN,NaN,1021.3,5.1,22.3,NaN,NaN,12.0,3.7
4,2019-04-01,AT,Innsbruck,NaN,0.1,5.0,75.7,NaN,36.6,NaN,...,NaN,NaN,NaN,1019.0,1.1,19.5,NaN,NaN,12.0,5.9

In [109]:
data_df_2019_Q2.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              50092
co               18780
dew              13355
humidity           229
mepaqi           51331
no2               9320
o3               10834
pm1              51268
pm10             10047
pm25              8810
pol              51067
precipitation    47158
pressure           501
so2              15164
temperature        207
uvi              50526
wd               47337
wind-gust        16360
wind-speed        1709
dtype: int64

# 2019_Q3

In [110]:
# Loading the data
raw_data_2019_Q3 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2019Q3.csv")

# print the shape
print(raw_data_2019_Q3.shape)

#runs the first 5 rows
raw_data_2019_Q3.head(10)

(582606, 5)

        Date Country    City Specie   max
0  8/20/2019      SK  Košice    dew  18.5
1  8/22/2019      SK  Košice    dew  14.5
2  9/20/2019      SK  Košice    dew   4.5
3  9/27/2019      SK  Košice    dew  12.5
4  10/1/2019      SK  Košice    dew   8.0
5   7/8/2019      SK  Košice    dew  13.0
6   8/3/2019      SK  Košice    dew  16.0
7  7/21/2019      SK  Košice    dew  18.5
8  7/23/2019      SK  Košice    dew  15.0
9  8/11/2019      SK  Košice    dew  18.5

In [111]:
# Convert 'Date' to datetime
raw_data_2019_Q3['Date'] = pd.to_datetime(raw_data_2019_Q3['Date'])

In [112]:
raw_data_2019_Q3.shape

(582606, 5)

In [113]:
# Pivot the data
data_df_2019_Q3 = raw_data_2019_Q3.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [114]:
print(data_df_2019_Q3.shape)
data_df_2019_Q3.head()

(57230, 22)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,no2,o3,...,pm25,pol,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2019-07-01,AE,Abu Dhabi,NaN,NaN,26.0,70.0,NaN,NaN,15.1,...,165.0,NaN,NaN,997.0,NaN,44.0,NaN,NaN,NaN,7.2
1,2019-07-01,AE,Dubai,NaN,NaN,26.0,62.0,NaN,NaN,NaN,...,159.0,NaN,NaN,997.0,NaN,41.0,NaN,NaN,NaN,7.2
2,2019-07-01,AR,Buenos Aires,NaN,10.3,4.1,90.2,NaN,15.1,10.6,...,85.0,NaN,NaN,1024.5,NaN,12.7,NaN,337.5,15.8,10.0
3,2019-07-01,AT,Graz,NaN,0.1,20.0,95.0,NaN,33.4,NaN,...,NaN,NaN,NaN,1019.8,16.8,33.8,NaN,NaN,11.3,5.6
4,2019-07-01,AT,Innsbruck,NaN,0.1,18.5,91.3,NaN,27.5,NaN,...,NaN,NaN,NaN,1021.5,1.1,31.5,NaN,NaN,15.0,7.2

In [115]:
data_df_2019_Q3.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              55734
co               21758
dew              14427
humidity            74
mepaqi           57132
no2              10192
o3               12979
pm1              57100
pm10             10728
pm25              9627
pol              56146
precipitation    52356
pressure           530
so2              17234
temperature         67
uvi              56261
wd               52620
wind-gust        18819
wind-speed         980
dtype: int64

# 2019_Q4

In [116]:
# Loading the data
raw_data_2019_Q4 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2019Q4.csv")

# print the shape
print(raw_data_2019_Q4.shape)

#runs the first 5 rows
raw_data_2019_Q4.head(10)

(578226, 5)

         Date Country      City Specie   max
0   11/2/2019      HU  Debrecen     o3  12.2
1  11/11/2019      HU  Debrecen     o3  15.2
2  11/12/2019      HU  Debrecen     o3  18.9
3  12/22/2019      HU  Debrecen     o3  24.1
4    1/5/2020      HU  Debrecen     o3  26.4
5   10/4/2019      HU  Debrecen     o3  25.6
6   10/9/2019      HU  Debrecen     o3  35.2
7  11/20/2019      HU  Debrecen     o3  24.7
8  12/11/2019      HU  Debrecen     o3  24.4
9  12/15/2019      HU  Debrecen     o3  16.8

In [117]:
# Convert 'Date' to datetime
raw_data_2019_Q4['Date'] = pd.to_datetime(raw_data_2019_Q4['Date'])

In [118]:
raw_data_2019_Q4.shape

(578226, 5)

In [119]:
# Pivot the data
data_df_2019_Q4 = raw_data_2019_Q4.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [120]:
print(data_df_2019_Q4.shape)
data_df_2019_Q1.head()

(57861, 25)

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,no2,o3,...,pm25,pol,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2018-12-31,AE,Abu Dhabi,NaN,NaN,19.0,94.0,NaN,49.4,56.5,...,152.0,NaN,NaN,1021.0,27.9,27.0,NaN,NaN,NaN,6.1
1,2018-12-31,AR,Buenos Aires,NaN,NaN,21.0,78.0,NaN,NaN,NaN,...,NaN,NaN,NaN,1011.0,NaN,23.8,NaN,0.0,188.2,17.3
2,2018-12-31,AT,Graz,NaN,0.1,NaN,82.0,NaN,35.2,NaN,...,NaN,NaN,NaN,1043.7,2.6,9.0,NaN,NaN,8.6,4.5
3,2018-12-31,AT,Innsbruck,NaN,0.1,0.5,100.0,NaN,42.5,NaN,...,NaN,NaN,NaN,1034.5,1.8,2.2,NaN,NaN,23.3,11.3
4,2018-12-31,AT,Linz,NaN,0.1,3.0,100.0,NaN,18.3,NaN,...,82.0,NaN,NaN,1036.9,17.3,5.1,NaN,NaN,11.7,6.9

In [121]:
data_df_2019_Q4.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              56388
co               21943
dew              16361
humidity          2755
mepaqi           57763
neph             57795
no2              10772
o3               13984
pm1              57569
pm10             10930
pm25              9774
pol              56418
precipitation    54213
pressure          3069
so2              17888
temperature       2730
uvi              56952
wd               53664
wind gust        54986
wind speed       53344
wind-gust        21844
wind-speed        3574
dtype: int64

# 2018_H1

In [122]:
# Loading the data
raw_data_2018_H1 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2018H1.csv")

# print the shape
print(raw_data_2018_H1.shape)

#runs the first 5 rows
raw_data_2018_H1.head(10)

(552440, 5)

        Date Country    City Specie   max
0  4/19/2018      HR  Zagreb   pm10  66.0
1   5/3/2018      HR  Zagreb   pm10  46.0
2   5/8/2018      HR  Zagreb   pm10  33.0
3  5/31/2018      HR  Zagreb   pm10  60.0
4  6/22/2018      HR  Zagreb   pm10  60.0
5   3/2/2018      HR  Zagreb   pm10  72.0
6  2/20/2018      HR  Zagreb   pm10  21.0
7  2/23/2018      HR  Zagreb   pm10  26.0
8  3/12/2018      HR  Zagreb   pm10  68.0
9  3/25/2018      HR  Zagreb   pm10  46.0

In [123]:
# Convert 'Date' to datetime
raw_data_2018_H1['Date'] = pd.to_datetime(raw_data_2018_H1['Date'])

In [124]:
raw_data_2018_H1.shape

(552440, 5)

In [125]:
# Pivot the data
data_df_2018_H1 = raw_data_2018_H1.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [126]:
print(data_df_2018_H1.shape)
data_df_2018_H1.head()

(92410, 22)

Specie,Date,Country,City,aqi,co,d,humidity,mepaqi,no2,o3,...,pm25,pol,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2018-01-01,AE,Abu Dhabi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,119.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-01-01,AR,Buenos Aires,NaN,7.3,NaN,NaN,NaN,14.2,15.1,...,85.0,NaN,NaN,NaN,2.1,NaN,NaN,NaN,NaN,NaN
2,2018-01-01,AT,Graz,NaN,0.1,NaN,NaN,NaN,43.9,NaN,...,NaN,NaN,NaN,NaN,10.9,NaN,NaN,NaN,NaN,NaN
3,2018-01-01,AT,Innsbruck,NaN,0.1,NaN,NaN,NaN,33.9,NaN,...,NaN,NaN,NaN,NaN,2.1,NaN,NaN,NaN,NaN,NaN
4,2018-01-01,AT,Linz,NaN,0.1,NaN,NaN,NaN,38.4,NaN,...,390.0,NaN,NaN,NaN,17.3,NaN,NaN,NaN,NaN,NaN

In [127]:
data_df_2018_H1.isnull().sum()

Specie
Date                 0
Country              0
City                 0
aqi              89157
co               32652
d                90397
humidity         68770
mepaqi           92232
no2              12867
o3               16072
pm1              92249
pm10             16901
pm25             16184
pol              91979
precipitation    90576
pressure         69101
so2              27288
temperature      68764
uvi              90294
wd               88246
wind-gust        77551
wind-speed       72070
dtype: int64

# 2017_H1

In [128]:
# Loading the data
raw_data_2017_H1 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2017H1.csv")

# print the shape
print(raw_data_2017_H1.shape)

#runs the first 5 rows
raw_data_2017_H1.head(10)

(427974, 5)

         Date Country     City Specie    max
0  12/27/2016      CN  Beijing     co   34.4
1   1/28/2017      CN  Beijing     co   49.7
2   2/24/2017      CN  Beijing     co   37.1
3   3/18/2017      CN  Beijing     co   29.0
4   4/16/2017      CN  Beijing     co   17.2
5   6/12/2017      CN  Beijing     co   46.1
6   2/16/2017      CN  Beijing     co   41.6
7    3/6/2017      CN  Beijing     co  101.6
8   4/29/2017      CN  Beijing     co   15.4
9    6/3/2017      CN  Beijing     co   12.7

In [129]:
# Convert 'Date' to datetime
raw_data_2017_H1['Date'] = pd.to_datetime(raw_data_2017_H1['Date'])

In [130]:
raw_data_2017_H1.shape

(427974, 5)

In [131]:
# Pivot the data
data_df_2017_H1 = raw_data_2017_H1.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [132]:
print(data_df_2017_H1.shape)
data_df_2017_H1.head()

(88640, 21)

Specie,Date,Country,City,aqi,co,d,humidity,mepaqi,neph,no2,...,pm1,pm10,pm25,pol,pressure,so2,temperature,uvi,wd,wind-speed
0,2016-12-26,AR,Buenos Aires,NaN,0.1,NaN,NaN,NaN,NaN,NaN,...,NaN,38.0,87.0,NaN,NaN,11.2,NaN,NaN,NaN,NaN
1,2016-12-26,AT,Graz,NaN,0.1,NaN,NaN,NaN,NaN,40.3,...,NaN,115.0,NaN,NaN,NaN,8.7,NaN,NaN,NaN,NaN
2,2016-12-26,AT,Innsbruck,NaN,0.1,NaN,NaN,NaN,NaN,37.5,...,NaN,44.0,NaN,NaN,NaN,5.6,NaN,NaN,NaN,NaN
3,2016-12-26,AT,Linz,NaN,0.1,NaN,NaN,NaN,NaN,28.6,...,NaN,18.0,59.0,NaN,NaN,15.2,NaN,NaN,NaN,NaN
4,2016-12-26,AT,Salzburg,NaN,0.1,NaN,NaN,NaN,NaN,34.8,...,NaN,58.0,NaN,NaN,NaN,2.6,NaN,NaN,NaN,NaN

In [133]:
data_df_2017_H1.isnull().sum()

Specie
Date               0
Country            0
City               0
aqi            86591
co             30374
d              88622
humidity       88493
mepaqi         88451
neph           88100
no2            10738
o3             12809
pm1            88425
pm10           16164
pm25           13666
pol            88438
pressure       88507
so2            25932
temperature    88493
uvi            86525
wd             88610
wind-speed     88608
dtype: int64

# 2016_H1

In [134]:
# Loading the data
raw_data_2016_H1 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2016H1.csv")

# print the shape
print(raw_data_2016_H1.shape)

#runs the first 5 rows
raw_data_2016_H1.head(10)

(413840, 5)

        Date Country       City Specie   max
0   2/3/2016      SE  Stockholm     o3  23.1
1   2/4/2016      SE  Stockholm     o3  25.7
2  2/16/2016      SE  Stockholm     o3  21.1
3  3/11/2016      SE  Stockholm     o3  29.2
4   4/2/2016      SE  Stockholm     o3  27.0
5   5/2/2016      SE  Stockholm     o3  42.6
6  5/11/2016      SE  Stockholm     o3  32.3
7   1/4/2016      SE  Stockholm     o3  21.9
8  5/26/2016      SE  Stockholm     o3  28.2
9  6/18/2016      SE  Stockholm     o3  27.8

In [135]:
# Convert 'Date' to datetime
raw_data_2016_H1['Date'] = pd.to_datetime(raw_data_2016_H1['Date'])

In [136]:
raw_data_2016_H1.shape

(413840, 5)

In [137]:
# Pivot the data
data_df_2016_H1 = raw_data_2016_H1.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [138]:
print(data_df_2016_H1.shape)
data_df_2016_H1.head()

(86762, 15)

Specie,Date,Country,City,aqi,co,mepaqi,neph,no2,o3,pm10,pm25,pol,psi,so2,uvi
0,2015-12-28,AE,Dubai,NaN,21.8,NaN,NaN,94.0,49.8,28.0,177.0,NaN,NaN,500.0,NaN
1,2015-12-28,AT,Graz,NaN,0.1,NaN,NaN,54.9,NaN,90.0,NaN,NaN,NaN,24.9,NaN
2,2015-12-28,AT,Innsbruck,NaN,0.1,NaN,NaN,82.6,NaN,137.0,NaN,NaN,NaN,5.6,NaN
3,2015-12-28,AT,Linz,NaN,0.1,NaN,NaN,39.4,NaN,164.0,340.0,NaN,NaN,7.4,NaN
4,2015-12-28,AT,Salzburg,NaN,0.1,NaN,NaN,66.5,NaN,92.0,NaN,NaN,NaN,20.8,NaN

In [139]:
data_df_2016_H1.isnull().sum()

Specie
Date           0
Country        0
City           0
aqi        83470
co         30320
mepaqi     86575
neph       86753
no2        11241
o3         12670
pm10       15432
pm25       17453
pol        86227
psi        86575
so2        25835
uvi        84753
dtype: int64

# 2015_H1

In [140]:
# Loading the data
raw_data_2015_H1 = pd.read_csv(r"/kaggle/input/raw-data/airqualitydata-2015H1.csv")

# print the shape
print(raw_data_2015_H1.shape)

#runs the first 5 rows
raw_data_2015_H1.head(10)

(388980, 5)

        Date Country    City Specie   max
0   1/6/2015      KR  Jeonju     co  12.3
1  1/22/2015      KR  Jeonju     co  10.0
2  3/30/2015      KR  Jeonju     co  11.2
3  5/27/2015      KR  Jeonju     co   5.6
4   2/3/2015      KR  Jeonju     co  13.4
5  2/11/2015      KR  Jeonju     co  11.2
6  2/18/2015      KR  Jeonju     co   8.9
7   3/5/2015      KR  Jeonju     co  12.3
8  3/19/2015      KR  Jeonju     co   7.8
9   4/4/2015      KR  Jeonju     co  10.0

In [141]:
# Convert 'Date' to datetime
raw_data_2015_H1['Date'] = pd.to_datetime(raw_data_2015_H1['Date'])

In [142]:
raw_data_2015_H1.shape

(388980, 5)

In [143]:
# Pivot the data
data_df_2015_H1 = raw_data_2015_H1.pivot_table(
    index=['Date', 'Country', 'City'],  # Grouping columns
    columns='Specie',                  # Unique values become columns
    values='max',                   # Values to aggregate
    aggfunc='mean'                     # Aggregation function
).reset_index()

In [144]:
print(data_df_2015_H1.shape)
data_df_2015_H1.head()

(83090, 14)

Specie,Date,Country,City,aqi,co,mepaqi,neph,no2,o3,pm10,pm25,psi,so2,uvi
0,2014-12-29,AT,Graz,NaN,0.1,NaN,NaN,52.5,NaN,116.0,NaN,NaN,4.6,NaN
1,2014-12-29,AT,Innsbruck,NaN,0.1,NaN,NaN,46.7,NaN,39.0,NaN,NaN,2.1,NaN
2,2014-12-29,AT,Linz,NaN,0.1,NaN,NaN,34.3,NaN,50.0,102.0,NaN,21.8,NaN
3,2014-12-29,AT,Salzburg,NaN,0.1,NaN,NaN,43.0,NaN,46.0,NaN,NaN,3.6,NaN
4,2014-12-29,AT,Vienna,NaN,0.1,NaN,NaN,22.9,NaN,37.0,80.0,NaN,4.1,NaN

In [145]:
data_df_2015_H1.isnull().sum()

Specie
Date           0
Country        0
City           0
aqi        80383
co         30736
mepaqi     82901
neph       82526
no2        12888
o3         14612
pm10       14221
pm25       18769
psi        82914
so2        24251
uvi        80809
dtype: int64

# **Combine 2015-2024**

In [146]:
data_2015_2024 = pd.concat([data_df_2015_H1, data_df_2016_H1, data_df_2017_H1, data_df_2018_H1,
                            data_df_2019_Q1, data_df_2019_Q2, data_df_2019_Q3, data_df_2019_Q4,
                            data_df_2020_Q1, data_df_2020_Q2, data_df_2020_Q3, data_df_2020_Q4,
                            data_df_2021_Q1, data_df_2021_Q2, data_df_2021_Q3, data_df_2021_Q4,
                            data_df_2022_Q2, data_df_2022_Q3, data_df_2022_Q4,
                            data_df_2023_Q1, data_df_2023_Q2, data_df_2023_Q3, data_df_2023_Q4,
                            data_df_2024], ignore_index=True)

In [147]:
data_2015_2024.shape

(1462740, 27)

In [148]:
data_2015_2024.isnull().sum()

Specie
Date                   0
Country                0
City                   0
aqi              1427395
co                540346
mepaqi           1460151
neph             1458086
no2               253816
o3                320411
pm10              268219
pm25              228850
psi              1462377
so2               455441
uvi              1433423
pol              1457782
d                1460709
humidity          353140
pm1              1457366
pressure          356910
temperature       352246
wd               1380269
wind-speed        415811
precipitation    1337548
wind-gust         848792
dew               615695
wind gust        1430975
wind speed       1412989
dtype: int64

In [149]:
data_2015_2024.head()

Specie,Date,Country,City,aqi,co,mepaqi,neph,no2,o3,pm10,...,pm1,pressure,temperature,wd,wind-speed,precipitation,wind-gust,dew,wind gust,wind speed
0,2014-12-29,AT,Graz,NaN,0.1,NaN,NaN,52.5,NaN,116.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2014-12-29,AT,Innsbruck,NaN,0.1,NaN,NaN,46.7,NaN,39.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2014-12-29,AT,Linz,NaN,0.1,NaN,NaN,34.3,NaN,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2014-12-29,AT,Salzburg,NaN,0.1,NaN,NaN,43.0,NaN,46.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2014-12-29,AT,Vienna,NaN,0.1,NaN,NaN,22.9,NaN,37.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [150]:
# Find the minimum and maximum dates
min_date = data_2015_2024['Date'].min()
max_date = data_2015_2024['Date'].max()

print('Minimum date:', min_date)
print('Maximum date:', max_date)

Minimum date: 2014-12-29 00:00:00
Maximum date: 2024-12-31 00:00:00

In [151]:
import os

In [152]:
os.makedirs('/kaggle/working', exist_ok=True)
data_2015_2024.to_csv('/kaggle/working/data_2015_2024.csv')

**Combine 2021-2024**

In [153]:
data_2021_2024 = pd.concat([data_df_2021_Q1, data_df_2021_Q2, data_df_2021_Q3, data_df_2021_Q4,
                            data_df_2022_Q2, data_df_2022_Q3, data_df_2022_Q4,
                            data_df_2023_Q1, data_df_2023_Q2, data_df_2023_Q3, data_df_2023_Q4,
                            data_df_2024], ignore_index=True)

In [154]:
data_2021_2024.shape

(660217, 22)

In [155]:
data_2021_2024.isnull().sum()

Specie
Date                  0
Country               0
City                  0
aqi              647547
co               248282
dew              139750
humidity          10864
mepaqi           659140
neph             657526
no2              123641
o3               159519
pm1              657298
pm10             120443
pm25              89541
precipitation    578292
pressure          12102
so2              212662
temperature       10082
uvi              646956
wd               617682
wind-gust        300728
wind-speed        20316
dtype: int64

In [156]:
data_2021_2024.head()

Specie,Date,Country,City,aqi,co,dew,humidity,mepaqi,neph,no2,...,pm10,pm25,precipitation,pressure,so2,temperature,uvi,wd,wind-gust,wind-speed
0,2020-12-28,AE,Abu Dhabi,NaN,0.1,16.0,73.0,NaN,NaN,38.9,...,113.0,65.0,NaN,1022.0,9.2,25.0,NaN,NaN,NaN,5.6
1,2020-12-28,AE,Dubai,NaN,NaN,11.0,52.0,NaN,NaN,NaN,...,NaN,72.0,NaN,1022.0,NaN,25.0,NaN,NaN,NaN,5.6
2,2020-12-28,AF,Kabul,NaN,NaN,-10.0,68.0,NaN,NaN,NaN,...,NaN,384.0,NaN,1022.0,NaN,7.0,NaN,NaN,NaN,7.2
3,2020-12-28,AR,Buenos Aires,NaN,5.5,22.5,87.0,NaN,NaN,17.9,...,35.0,104.0,NaN,1031.5,NaN,31.9,NaN,135.0,18.3,9.7
4,2020-12-28,AT,Graz,NaN,0.1,0.1,99.0,NaN,NaN,28.4,...,31.0,NaN,99.5,997.5,1.8,2.0,NaN,NaN,4.1,2.0

In [157]:
# Find the minimum and maximum dates
min_date = data_2021_2024['Date'].min()
max_date = data_2021_2024['Date'].max()

print('Minimum date:', min_date)
print('Maximum date:', max_date)

Minimum date: 2020-12-28 00:00:00
Maximum date: 2024-12-31 00:00:00

In [158]:
os.makedirs('/kaggle/working', exist_ok=True)
data_2021_2024.to_csv('/kaggle/working/data_2021_2024.csv')